### ISSUE TITLE
NSIS job fails when attempting to run

### ISSUE THREAD

**Issue by dammejed** [development-bizeta-mestre/nsis-extension#10]
Hello,

Since the version of this extension was automatically updated to 1.1.8 today, attempting to run any job fails with status similar to the following job output:

```
Starting: Include Nsis
==============================================================================
Task         : Nsis
Description  : Run Nsis
Version      : 1.1.8
Author       : bizeta
Help         : Run Nsis [More Information](https://github.com/dev-maxima/nsis-extension)
==============================================================================
##[error]File not found: 'C:\a\_work\_tasks\nsis_a459f79f-b932-4ebc-ae19-060fd656b294\1.1.8\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
Finishing: Include Nsis
```

**Comment by dzoccarato** [comment]
Hi @dammejed, sorry for this issue. We just publish an update. The version is 1.1.9 now.
Please try again and let us know if works now.

Davide

**Comment by dammejed** [comment]
@dzoccarato Thanks for the quick turnaround.
I confirm that the error disappears with 1.1.9. 

Thanks again!
